% Simulation of Powergrid

function [png] = powergrid_pdf()

png.PN_name = 'Powergrid Simulation';
png.set_of_Ps = {...
    'JNW','RBL','ZAG','KDN','ANI','GUA','WRZ','BLE','SIK','KAW','KLP',...
    'KLO','PAN','PRA','OLE','SOW','DBR','LBN','HER','ZWA','KOT',...
    'KNC','JLK','POH','MIJ','PRJ','RUD','RED','HCW',...
    'KOL1_W1', 'KOL1_W1','KOL1_W2', 'KOL1_W3', 'KOL1_W4',...
    'KOL1_Z1', 'KOL1_Z1', 'KOL1_Z3', 'KOL1_Z4', 'KOL2_Z1', 'KOL2_Z2',...
    'KOL2_Z2', 'KOL2_Z3', 'KOL2_Z4', 'KOL2_Z5', 'KOL2_Z6', 'KOL2_W1',...
    'KOL2_W2', 'KOL2_W3', 'KOL2_W4', 'KOL2_W5', 'KOL2_W6', 'KOL3_W1',...
    'KOL3_W2', 'KOL3_W3', 'KOL3_Z1', 'KOL3_Z2', 'KOL3_Z3', ...
};

png.set_of_Ts = {...
    'tGEN_3','tGEN_4','tGEN_AT1',...
    'tKDN_2_ZAG','tZAG_2_KDN','tZAG_2_KLO','tKLO_2_ZAG','tKLO_2_PAN','tPAN_2_KLO',...
    'tPAN_2_PRA','tPRA_2_PAN','tPRA_2_OLE','tOLE_2_PRA','tOLE_2_SOW','tSOW_2_OLE',...
    'tSOW_2_DBR','tDBR_2_SOW','tDBR_2_LBN','tLBN_2_HER',...
    'tKLO_2_KLP','tKLP_2_KLO','tKLP_2_KAW','tBLE_2_WRZ','tWRZ_2_BLE'...
	'tRED_2_RUD','tRUD_2_RED','tPRJ_2_MIJ','tMIJ_2_PRJ','tMIJ_2_POH','tPOH_2_MIJ',...
	'tPOH_2_KOT','tKOT_2_POH','tKOT_2_ZWA','tZWA_2_KOT','tZWA_2_SKC','tSKC_2_ZWA',...
	'tSKC_2_KNC','tKNC_2_SKC','tKNC_2_JLK','tJLK_2_KNC',...    
};

png.set_of_As = {...
%    'GEN_3',?,1,    ... % Generator 3 empty transition
%    'GEN_4',?,1,    ... % Generator 4 empty transition
     'pStart','tColor',1, 'tColor','pCombined',1,   ... % tColor
    'pCombined','tA',1, 'tA','pA',1 ...                % tA
    'pCombined','tA_or_B',1, 'tA_or_B','pA_or_B',1 ... % tA_or_B
    'pCombined','tA_or_B_Preferred',1, ...             % tA_or_B_Preferred
         'tA_or_B_Preferred','pA_or_B_Preferred',1 ... % tA_or_B_Preferred
    'pCombined','tA_and_B',1, 'tA_and_B','pA_and_B',1 ... % tA_and_B    
                };
